### PR TITLE
Fix height bug

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg This plugin works AWESOME now. And it boots the whole evolution process. Like this:

screenshot from 2016-02-01 11 21 36

**Comment by nsg** [comment]
@petterarvidsson indeed, really awesome! Looking forward to try it this evening.

**Comment by nsg** [comment]
@petterarvidsson I added a proper fix with a growth patten like I intended it. It only looks at the N, W, S, E corners in a block-y fashion. I tried to make the code as clear as possible consider that this is a good demo plugin.

**Comment by petterarvidsson** [comment]
@nsg Nice!

**Pull request merged**
